import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomePageHeader from "@/components/layout/header/home/HomePageHeader";
import HomePageFooter from "@/components/layout/footer/home/HomePageFooter";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased flex flex-col justify-between`}
    >
 
      <body className="min-h-full flex flex-col">
        <HomePageHeader />
        {children}
        <HomePageFooter />
      </body>
      
    </html>
  );
}
